

all:
	$(MAKE) -C misc all
	$(MAKE) -C array all
	$(MAKE) -C tuple all
	$(MAKE) -C iterable all

clean:
	$(MAKE) -C misc clean
	$(MAKE) -C array clean
	$(MAKE) -C tuple clean
	$(MAKE) -C iterable clean
